[workspace]
members = ["lukin", "pali", "poki", "sama"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Morgan Arnold <morgan.arnold@proton.me>"]
edition = "2021"
repository = "https://codeberg.org/mra/ilo-binutils"
license = "Unlicense"
