[package]
name = "poki"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "a library for serializing and deserializing the poki relocatable binary format"
repository.workspace = true
license.workspace = true
